### ISSUE TITLE
12.02.2022-task yerine yetirilib

### ISSUE THREAD

**Issue by Bayramzade066** [RaviHamidov/PragmatechFrontEndProject#1]
folder yoxlanildi, taskda istenilen button novleri yazilib, elave olaraq sass istifade olunub, ortaq classlar istifade olunub, NOT: a taginin daxilinde button tagi yaradilsa ve classlar ona verilse daha meqsede uygun olardi, (yazdiginiz formadada uygundur).| bir sozle taskda teleb olunanlar yerine yetirilib.

**Comment by RaviHamidov** [comment]
Task Tam olaraq yerine yetirildi
